image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production
variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  REPO: vstaf/reddit

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo 'Building'
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - docker build -t $REPO:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID docker-monolith
    - docker push $REPO:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID

test_unit_job:
  before_script:
  - cd reddit
  - bundle install
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  image: docker:latest
  stage: review
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - apk update
    - apk add openssl curl
    - echo $GCE_JSON > key.json && export GOOGLE_APPLICATION_CREDENTIALS=key.json
    - curl -L https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && chmod +x /tmp/docker-machine && cp /tmp/docker-machine ~/docker-machine
    - ~/docker-machine create --driver google --google-project "${GCP_PROJECT}"
      --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts 
      --google-machine-type n1-standard-1 
      --google-disk-size "10" 
      --google-tags docker-host 
      --google-zone "${GCP_ZONE}" "${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}"
    - eval $(~/docker-machine env --shell sh ${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID})
    - docker run -d -p 9292:9292 --name reddit $REPO:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

stop_review:
  stage: review
  image: google/cloud-sdk:alpine
  script:
    - echo $GCE_JSON > key.json && export GOOGLE_APPLICATION_CREDENTIALS=key.json
    - gcloud auth activate-service-account --key-file=key.json --project=${GCP_PROJECT}
    - gcloud compute instances delete "${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}" --zone=${GCP_ZONE} --quiet
  when: manual
  environment:
    name: branch/$CI_COMMIT_REF_NAME


staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
