global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir.stafievsky'
