kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: mFBThYe/bfnofVMh7lAjPRsqwgdzlWLpo33cz9PjEg4=
      - identity: {}
