# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kibana:
  env:
    ELASTICSEARCH_URL: "http://elasticsearch-logging:9200"
  ingress:
    enabled: true
    hosts: 
      - reddit-kibana

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
